# ----------------------------------------------------------------------------
# Copyright (c) 2021-2026 DexForce Technology Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------

import torch
from typing import Dict, Optional

from embodichain.lab.gym.envs import EmbodiedEnv, EmbodiedEnvCfg
from embodichain.lab.sim.cfg import RigidConstraintCfg
from embodichain.lab.gym.utils.registration import register_env
from embodichain.utils import logger
from robosynchallenge.managers.events import visualize_rigid_body_pose
from embodichain_tasks.tableware.base_agent_env import BaseAgentEnv
from .action_bank import (
    ItemAssemblyActionBank,
)

__all__ = ["ItemAssemblyEnv", "ItemAssemblyAgentEnv"]


@register_env("ItemAssembly", max_episode_steps=600)
class ItemAssemblyEnv(EmbodiedEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)

        action_config = kwargs.get("action_config", None)
        if action_config is not None:
            self.action_config = action_config
        # per-env attach flag so we don't re-attach already-welded arenas
        self._guijiao_attached = torch.zeros(self.num_envs, dtype=torch.bool, device=self.device)
        # optional global step to wait before allowing attach (scheduled from packages)
        self._guijiao_attach_step = None
        self._guijiao_attach_schedule_checked = False

        self._success_flag = torch.zeros(
            self.num_envs, dtype=torch.bool, device=self.device
        )

    def create_demo_action_list(self, *args, **kwargs):
        """
        Create a demonstration action list for the current task.

        Returns:
            list: A list of demo actions generated by the task.
        """
        logger.log_info("Create demo action list for ItemAssembly Task.")

        if getattr(self, "action_config") is not None:
            self._init_action_bank(ItemAssemblyActionBank, self.action_config)
            action_list = self.create_expert_demo_action_list(*args, **kwargs)
        else:
            logger.log_error("No action_config found in env, please check again.")

        if action_list is None:
            return action_list

        logger.log_info(
            f"Demo action list created with {len(action_list)} steps.", color="green"
        )
        return action_list

    def create_expert_demo_action_list(self, **kwargs):
        """
        Create an expert demonstration action list using the action bank.

        This function generates a trajectory based on expert knowledge, mapping joint and end-effector
        states to the required action format for the environment and robot type.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            list: A list of actions, each containing joint positions ("qpos").
        """

        if hasattr(self, "action_bank") is False or self.action_bank is None:
            logger.log_error(
                "Action bank is not initialized. Cannot create expert demo action list."
            )

        ret = self.action_bank.create_action_list(
            self, self.graph_compose, self.packages
        )

        if ret is None:
            logger.log_warning("Failed to generate expert demo action list.")
            return None

            self._schedule_guijiao_attach_after_edge("L_splice_to_align")

        # TODO: to be removed, need a unified interface in robot class
        left_arm_joints = self.robot.get_joint_ids(name="left_arm", remove_mimic=True)
        right_arm_joints = self.robot.get_joint_ids(name="right_arm", remove_mimic=True)
        left_eef_joints = self.robot.get_joint_ids(name="left_eef", remove_mimic=True)
        right_eef_joints = self.robot.get_joint_ids(name="right_eef", remove_mimic=True)


        total_traj_num = ret[list(ret.keys())[0]].shape[-1]
        num_active_joints = len(self.active_joint_ids)
        actions = torch.zeros(
            (total_traj_num, self.num_envs, num_active_joints), dtype=torch.float32
        )

        global_to_active_idx = {
            joint_id: active_idx for active_idx, joint_id in enumerate(self.active_joint_ids)
        }

        for key, joints in [
            ("left_arm", left_arm_joints),
            ("left_eef", left_eef_joints),
            ("right_arm", right_arm_joints),
            ("right_eef", right_eef_joints),
        ]:
            if key in ret:
                # TODO: only 1 env supported now
                local_action_data = torch.as_tensor(ret[key].T, dtype=torch.float32)

                for i, joint_id in enumerate(joints):
                    if joint_id in global_to_active_idx:
                        active_idx = global_to_active_idx[joint_id]
                        actions[:, 0, active_idx] = local_action_data[:, i]
        return actions

    def _schedule_guijiao_attach_after_edge(self, edge_name: str):
        # reset per-env attach flags when (re)scheduling
        self._guijiao_attached = torch.zeros(self.num_envs, dtype=torch.bool, device=self.device)
        self._guijiao_attach_step = None
        self._guijiao_attach_schedule_checked = True
        package_infos = getattr(self, "packages", {}).get("packages", [])
        for package in package_infos:
            if package.get("label") == edge_name:
                self._guijiao_attach_step = int(package["end"])
                logger.log_info(
                    f"Scheduled guijiao attach after edge '{edge_name}' "
                    f"at step {self._guijiao_attach_step}."
                )
                return
        logger.log_warning(f"Cannot schedule guijiao attach: edge '{edge_name}' not found.")

    def _ensure_guijiao_attach_schedule(self):
        if self._guijiao_attach_schedule_checked:
            return
        if not hasattr(self, "packages"):
            action_config = getattr(self, "action_config", None)
            if action_config is None:
                self._guijiao_attach_schedule_checked = True
                return
            self._init_action_bank(ItemAssemblyActionBank, action_config)
        self._schedule_guijiao_attach_after_edge("L_splice_to_align")

    def _run_guijiao_attach_if_ready(self):
        """Check contact per-env and attach only those arenas that need it.

        Uses the event functor `attach_guijiao` (defined in gym_config) so the
        operation creates a proper rigid constraint in the sim layer instead of
        using low-level node attach (which caused PhysX warnings).
        """
        self._ensure_guijiao_attach_schedule()

        # compute per-env contact mask
        try:
            sensor = self.sim.get_sensor("guijiao_contact")
        except Exception:
            return

        try:
            data = sensor.get_data()
        except Exception:
            return
        if data is None:
            return

        distances = data.get("distance")
        is_valid = data.get("is_valid")
        user_ids = data.get("user_ids")
        if distances is None or is_valid is None or user_ids is None:
            return

        # resolve guijiao user ids
        gu1 = self.sim.get_rigid_object("guijiao1")
        gu2 = self.sim.get_rigid_object("guijiao2")
        if gu1 is None or gu2 is None:
            return
        gu1_uids = gu1.get_user_ids().reshape(-1)
        gu2_uids = gu2.get_user_ids().reshape(-1)

        left_in_g1 = torch.isin(user_ids[:, :, 0], gu1_uids)
        right_in_g2 = torch.isin(user_ids[:, :, 1], gu2_uids)
        left_in_g2 = torch.isin(user_ids[:, :, 0], gu2_uids)
        right_in_g1 = torch.isin(user_ids[:, :, 1], gu1_uids)
        inter_mask = (left_in_g1 & right_in_g2) | (left_in_g2 & right_in_g1)

        effective = is_valid & inter_mask
        masked = torch.full_like(distances, float("inf"))
        masked[effective] = distances[effective]
        min_dist = masked.min(dim=1)[0]
        contact_mask = min_dist <= 0.003

        # additional axis-alignment check: require tube axes to be close (<=15deg)
        try:
            gu1_pose = gu1.get_local_pose(to_matrix=True)
            gu2_pose = gu2.get_local_pose(to_matrix=True)
            # extract local X axis (first column) for each env
            dir1 = gu1_pose[:, :3, 0]
            dir2 = gu2_pose[:, :3, 0]
            dot = torch.sum(dir1 * dir2, dim=-1)
            dot = torch.clamp(dot, -1.0, 1.0)
            angle = torch.acos(torch.abs(dot))
            angle_ok = angle <= (15.0 * torch.pi / 180.0)
        except Exception:
            # if pose unavailable, conservatively allow attach only by contact
            angle_ok = torch.ones_like(contact_mask, dtype=torch.bool)

        # final attach candidates: contact, alignment, and not already attached
        attach_mask = contact_mask & angle_ok & (~self._guijiao_attached)

        # if scheduled attach_step exists, require step >= schedule
        if self._guijiao_attach_step is not None and hasattr(self, "_elapsed_steps"):
            current_steps = self._elapsed_steps
            attach_mask = attach_mask & (current_steps >= int(self._guijiao_attach_step))

        attach_ids = attach_mask.nonzero(as_tuple=False).squeeze(-1)
        if attach_ids.numel() == 0:
            return

        # debug log distances and angles for attach candidates
        try:
            dbg_dists = min_dist[attach_ids].cpu().tolist()
        except Exception:
            dbg_dists = None
        try:
            dbg_angles = None
            if 'angle' in locals():
                dbg_angles = (angle[attach_ids].cpu().numpy() * 180.0 / torch.pi).tolist()
        except Exception:
            dbg_angles = None
        logger.log_info(f"Attaching guijiao for envs {attach_ids.tolist()} dists={dbg_dists} angles_deg={dbg_angles}")

        # call event functor to create rigid constraint for selected arenas
        applied = False
        if hasattr(self, "event_manager"):
            # sanity check: ensure mode exists
            try:
                if "attach_guijiao" not in self.event_manager.available_modes:
                    logger.log_warning("event_manager has no mode 'attach_guijiao'; will fallback to sim API.")
                else:
                    try:
                        self.event_manager.apply(mode="attach_guijiao", env_ids=attach_ids)
                        applied = True
                    except Exception:
                        logger.log_warning("attach_guijiao event failed; will fallback to sim API.")
            except Exception:
                # unavailable available_modes, attempt apply anyway
                try:
                    self.event_manager.apply(mode="attach_guijiao", env_ids=attach_ids)
                    applied = True
                except Exception:
                    logger.log_warning("attach_guijiao event failed; will fallback to sim API.")

        if not applied:
            # fallback: call sim.create_rigid_constraint directly for these envs
            try:
                cfg = RigidConstraintCfg(
                    name="guijiao_weld",
                    rigid_object_a_uid="guijiao1",
                    rigid_object_b_uid="guijiao2",
                    local_frame_a=None,
                    local_frame_b=None,
                )
                constraint = self.sim.create_rigid_constraint(cfg=cfg, env_ids=attach_ids)
                if constraint is None:
                    logger.log_warning(f"sim.create_rigid_constraint returned None for envs {attach_ids.tolist()}")
                else:
                    applied = True
                    logger.log_info(f"Created guijiao_weld constraint for envs {attach_ids.tolist()} via sim API")
            except Exception as e:
                logger.log_warning(f"sim.create_rigid_constraint failed: {e}")

        # mark attached envs if any method succeeded
        if applied:
            self._guijiao_attached[attach_ids] = True

    def step(self, action, **kwargs):
        obs, rewards, terminateds, truncateds, info = super().step(action, **kwargs)
        # attach if contact detected this step
        self._run_guijiao_attach_if_ready()
        return obs, rewards, terminateds, truncateds, info


    def compute_task_state(self, **kwargs):
        try:
            guijiao1 = self.sim.get_rigid_object("guijiao1")
            guijiao2 = self.sim.get_rigid_object("guijiao2")
            guijiao1_pose = guijiao1.get_local_pose(to_matrix=True)
            guijiao2_pose = guijiao2.get_local_pose(to_matrix=True)
        except Exception:
            # If objects cannot be retrieved, no env is successful.
            guijiao1_pose = None
            guijiao2_pose = None

        num_envs = self.num_envs
        device = self.device
        # Basic validity checks: poses must be finite and have correct shape
        if guijiao1_pose is None or guijiao2_pose is None:
            metrics = {}
            fail = torch.zeros_like(self._success_flag, dtype=torch.bool)
            success = torch.zeros_like(fail, dtype=torch.bool)
            return success, fail, metrics


        valid_pose_mask = torch.isfinite(guijiao1_pose).all(dim=(1, 2)) & torch.isfinite(
            guijiao2_pose
        ).all(dim=(1, 2))


        # Extract X-axis direction from rotation matrix (1st column of 3x3 rotation part)
        # The guijiao mesh's longest geometric axis is aligned with local X, use that for success check.
        guijiao1_direction = guijiao1_pose[:, :3, 0]
        guijiao2_direction = guijiao2_pose[:, :3, 0]

        # Compute dot product between direction vectors and clamp
        dot_product = torch.sum(guijiao1_direction * guijiao2_direction, dim=-1)
        dot_product = torch.clamp(dot_product, -1.0, 1.0)

        # Compute angle between the two directions; use abs to treat antiparallel as parallel
        angle = torch.acos(torch.abs(dot_product))

        # Check if angle is within 15 degrees (convert 15 degrees to radians)
        threshold_angle = torch.tensor(15.0 * torch.pi / 180.0, dtype=angle.dtype, device=device)
        angle_ok = angle <= threshold_angle

        # Avoid counting successes immediately at timestep 0 (or before minimal interaction)
        min_steps = int(getattr(self, "success_min_steps", 5))
        elapsed = getattr(self, "_elapsed_steps", None)
        if elapsed is None:
            # If no per-env elapsed info, require at least global min_steps by default
            step_mask = torch.ones(num_envs, dtype=torch.bool, device=device)
        else:
            # _elapsed_steps is expected to be a tensor of shape (num_envs,)
            step_mask = elapsed >= min_steps

        # Contact-sensor based proximity check (prefer contact data when available)
        # Only contacts between guijiao1 and guijiao2 are considered valid for docking
        contact_ok = torch.ones(num_envs, dtype=torch.bool, device=device)
        min_contact_dist = None
        try:
            sensor = self.sim.get_sensor("guijiao_contact")
        except Exception:
            sensor = None
        if sensor is not None:
            try:
                data = sensor.get_data()
            except Exception:
                data = None
            if data is not None:
                distances = data["distance"]
                is_valid = data["is_valid"]
                user_ids = data["user_ids"]
                guijiao1_uids = guijiao1.get_user_ids().reshape(-1)
                guijiao2_uids = guijiao2.get_user_ids().reshape(-1)

                left_in_g1 = torch.isin(user_ids[:, :, 0], guijiao1_uids)
                right_in_g2 = torch.isin(user_ids[:, :, 1], guijiao2_uids)
                left_in_g2 = torch.isin(user_ids[:, :, 0], guijiao2_uids)
                right_in_g1 = torch.isin(user_ids[:, :, 1], guijiao1_uids)
                # build mask for contacts where one side is guijiao1 and other is guijiao2
                # shape: (num_envs, max_contacts)
                mask_g1_g2 = (left_in_g1 & right_in_g2) | (left_in_g2 & right_in_g1)

                # only consider contacts that are valid and between the two objects
                effective_mask = is_valid & mask_g1_g2
                # default to +inf distances
                masked = torch.full_like(distances, float("inf"))
                masked[effective_mask] = distances[effective_mask]
                # min distance per env
                min_contact_dist = masked.min(dim=1)[0]
                contact_ok = min_contact_dist <= 0.003

        # Radial (lateral) offset check: ensure the two axes are near the same line
        # lateral_offset = || (c2-c1) - ((c2-c1)·a1) * a1 ||
        # require lateral_offset <= lateral_tol to be considered success
        lateral_tol_val = kwargs.get("lateral_tol", None)
        if lateral_tol_val is None:
            lateral_tol_val = getattr(self, "success_lateral_tol", 0.02)
        try:
            lateral_tol = torch.as_tensor(
                float(lateral_tol_val), dtype=guijiao1_pose.dtype, device=device
            )
        except Exception:
            lateral_tol = torch.tensor(
                0.01, dtype=guijiao1_pose.dtype, device=device
            )

        # world centers
        c1 = guijiao1_pose[:, :3, 3]
        c2 = guijiao2_pose[:, :3, 3]

        # ensure axis unit vectors
        a1 = guijiao1_direction
        a1_unit = a1 / a1.norm(dim=-1, keepdim=True).clamp_min(1e-8)
        diff = c2 - c1
        proj = a1_unit * (diff * a1_unit).sum(dim=-1, keepdim=True)
        lateral_offset = (diff - proj).norm(dim=-1)
        lateral_ok = lateral_offset <= lateral_tol

        current_success = angle_ok & valid_pose_mask & step_mask & contact_ok & lateral_ok

        self._success_flag = current_success

        metrics = {
            "guijiao_angle_deg": torch.rad2deg(angle),
            "guijiao_lateral_offset": lateral_offset,
            "guijiao_angle_ok": angle_ok,
            "guijiao_lateral_ok": lateral_ok,
        }
        if min_contact_dist is not None:
            metrics["guijiao_min_contact_dist"] = min_contact_dist
            metrics["guijiao_contact_ok"] = contact_ok

        fail = torch.zeros_like(self._success_flag, dtype=torch.bool)
        success = torch.zeros_like(fail, dtype=torch.bool)
        return success, fail, metrics

    def is_task_success(self, **kwargs) -> torch.Tensor:
        return self._success_flag

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        if options is None:
            options = {}
        reset_ids = options.get(
            "reset_ids",
            torch.arange(self.num_envs, dtype=torch.int32, device=self.device),
        )

        # Important: the base env reset does not automatically run a custom
        # "detach_guijiao" event. If we leave the welded constraint in place,
        # the next episode will still see guijiao1/guijiao2 attached together.
        if "guijiao_weld" in self.sim.get_rigid_constraint_uid_list():
            detached = False
            event_manager = getattr(self, "event_manager", None)
            if (
                event_manager is not None
                and "detach_guijiao" in event_manager.available_modes
            ):
                try:
                    event_manager.apply(mode="detach_guijiao", env_ids=reset_ids)
                    detached = True
                except Exception as exc:
                    logger.log_warning(
                        f"detach_guijiao event failed; falling back to sim API: {exc}"
                    )
            if not detached and "guijiao_weld" in self.sim.get_rigid_constraint_uid_list():
                self.sim.remove_rigid_constraint("guijiao_weld", env_ids=reset_ids)

        self._guijiao_attached[reset_ids] = False
        self._guijiao_attach_step = None
        self._guijiao_attach_schedule_checked = False

        obs, info = super().reset(seed=seed, options=options)
        self._guijiao_attached[reset_ids] = False
        self._success_flag[reset_ids] = False
        return obs, info


@register_env("ItemAssemblyAgent", max_episode_steps=600)
class ItemAssemblyAgentEnv(BaseAgentEnv, ItemAssemblyEnv):
    def __init__(self, cfg: EmbodiedEnvCfg = None, **kwargs):
        super().__init__(cfg, **kwargs)
        super()._init_agents(**kwargs)

    def reset(self, seed: Optional[int] = None, options: Optional[Dict] = None):
        obs, info = super().reset(seed=seed, options=options)
        super().get_states()
        return obs, info
